const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function dashboard(accounts) {
    const active = accounts.filter(row => row.expired === false).length;
    const expired = accounts.filter(row => row.expired === true).length;
    const time = value => value ? escape(new Date(value).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})) : 'Bilinmiyor';
    const rows = accounts.map(row => `<tr><td>${escape(row.username)}</td><td>${escape(row.server)}</td><td>${escape(row.profileId)}</td><td>${row.expired === true ? 'Süresi dolmuş' : row.expired === false ? 'Süresi dolmamış' : 'Süre bilinmiyor'}</td><td>${time(row.expiresAt)}</td><td>${time(row.savedAt)}</td></tr>`).join('');
    return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MSP2 · Kayıtlı hesaplar</title><style>
    :root{color-scheme:dark;font-family:system-ui,sans-serif;color:#eaf2ff;background:#0b1320}body{margin:0;padding:32px 18px}main{max-width:1200px;margin:auto;background:#111e30;border:1px solid #31425b;border-radius:18px;padding:28px}h1{margin:0 0 10px;font-size:30px}p{color:#b4c4da;line-height:1.6}.stats{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0}.stats span{background:#22374f;padding:14px;border-radius:10px}a{display:inline-block;color:#a4d8ff;margin:10px 0}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{padding:14px 10px;border-bottom:1px solid #31425b;text-align:left;overflow-wrap:anywhere}th{color:#9ed5ff}footer{color:#92a7c0;font-size:12px;margin-top:20px}
    </style></head><body><main><h1>Kayıtlı hesaplar</h1><p>Durumlar kayıtlı tokenın son kullanma tarihine göre hesaplanır. Oyunda çevrimiçi olma veya tokenın MSP tarafından hâlâ kabul edilme durumu kontrol edilmez.</p><div class="stats"><span>${accounts.length} kayıt</span><span>${active} süresi dolmamış</span><span>${expired} süresi dolmuş</span><span>${accounts.length-active-expired} süre bilinmiyor</span></div><a href="/bot">Listeyi yenile</a><div class="scroll"><table><thead><tr><th>Hesap</th><th>Sunucu</th><th>Profil ID</th><th>Token süresi</th><th>Son kullanım (İstanbul)</th><th>Kayıt zamanı (İstanbul)</th></tr></thead><tbody>${rows || '<tr><td colspan="6">Henüz kayıt yok.</td></tr>'}</tbody></table></div><footer>Son 5000 kayıt gösterilir. Bu hesap listesi herkese açıktır. Erişim tokenları bu sayfada gösterilmez.</footer></main></body></html>`;
}
